apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "department-chart.fullname" . }}
  labels:
    {{- include "department-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "department-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "department-chart.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "department-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: { { .Values.postgres.secretName } }
                  key: { { .Values.postgres.urlKey } }
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: { { .Values.postgres.secretName } }
                  key: { { .Values.postgres.usernameKey } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: { { .Values.postgres.secretName } }
                  key: { { .Values.postgres.passwordKey } }
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
